from django.contrib.auth.models import Group, Permission
from django.core.management.base import BaseCommand
from materialcleaner.settings import PERMISSIONS_FORBIDDEN_FOR_STAFF, PERMISSIONS_FOR_REGULARS

from materialcleaner.settings import ACCESS_POLICIES

# !!!
# TO HAVE PROPER PERMISSION IDs please MIGRATE DB acc. file:
# 0001_initial.py dated # Generated by Django 2.2.10 on 2020-03-12 08:53
# !!!
class Command(BaseCommand):
    help = 'Step 4 @ fill-in new DB.  Assign permissions to user-groups acc. ACCESS_POLICIES'
    
    def handle(self, *args, **options):
        permissions = Permission.objects.all()
        
        staff = Group.objects.get(name='staff')
        for perm in permissions:
            if not perm.codename in PERMISSIONS_FORBIDDEN_FOR_STAFF:
                staff.permissions.add(perm)
        staff.save()
        
        regular = Group.objects.get(name='regular')
        for perm in permissions:
            if perm.codename in PERMISSIONS_FOR_REGULARS:
                regular.permissions.add(perm)
        regular.save()
        
        self.stdout.write("DONE! Permissions assigned to user-groups acc. ACCESS_POLICIES")
