from django.contrib.auth.models import Group, Permission
from django.core.management.base import BaseCommand

from materialcleaner.settings import ACCESS_POLICIES

# Permissions acc. ACCESS POLICIES (constance: settings.ACCESS_POLICIES):
PERMISSIONS_FORBIDDEN_FOR_STAFFS = ['add_user',
                                    'change_user',
                                    'delete_user',
                                    'add_userdetail',
                                    'change_userdetail',
                                    'delete_userdetail',
                                    'add_logentry',
                                    'change_logentry',
                                    'delete_logentry',
                                    'add_group',
                                    'change_group',
                                    'delete_group',
                                    'add_permission',
                                    'change_permission',
                                    'delete_permission',
                                    'add_contenttype',
                                    'change_contenttype',
                                    'delete_contenttype',
                                    'add_session',
                                    'change_session',
                                    'delete_session',
                                    ]

PERMISSIONS_FOR_REGULARS = ['add_user',
                            'change_user',
                            'delete_user',
                            'view_user',
                            'add_userdetail',
                            'change_userdetail',
                            'delete_userdetail',
                            'view_userdetail',
                            'add_saleposter',
                            'change_saleposter',
                            'delete_saleposter',
                            'view_saleposter',
                            ]


# !!!
# TO HAVE PROPER PERMISSION IDs please MIGRATE DB acc. file:
# 0001_initial.py dated '# Generated by Django 2.2.10 on 2020-03-11 18:41'
# !!!
class Command(BaseCommand):
    help = 'Step 4 @ creating new DB.\n' \
           'Assign permissions to user-groups acc.: ' + ACCESS_POLICIES
    
    def handle(self, *args, **options):
        permissions = Permission.objects.all()
        
        staff = Group.objects.get(name='staff')
        for perm in permissions:
            if not perm.codename in PERMISSIONS_FORBIDDEN_FOR_STAFFS:
                staff.permissions.add(perm)
        staff.save()
        
        regular = Group.objects.get(name='regular')
        for perm in permissions:
            if perm.codename in PERMISSIONS_FOR_REGULARS:
                regular.permissions.add(perm)
        regular.save()
        
        self.stdout.write("SUCCESS! Permissions assigned to user-groups acc. ACCESS_POLICIES")
