from django.contrib.auth.models import Group, Permission
from django.core.management.base import BaseCommand

from materialcleaner.settings import ACCESS_POLICIES

# !!!
# TO HAVE PROPER PERMISSION IDs please MIGRATE DB acc. file:
# 0001_initial.py dated '# Generated by Django 2.2.10 on 2020-03-11 18:41'
# !!!
class Command(BaseCommand):
    help = 'Step 3 @ creating new DB.\n' \
           'Populate user-groups and define permissions' + ACCESS_POLICIES
    
    def handle(self, *args, **options):
        permissions = Permission.objects.all()
        staff = Group.objects.create(name='staff')
        
        regular = Group.objects.create(name='regular')
        
        self.stdout.write("SUCCESS! Groups created and permissions set acc. ACCESS_POLICIES")
